### ISSUE TITLE
Remove electron peer dependency

### ISSUE THREAD

**Issue by offirgolan** [daltonmenezes/electron-router-dom#1]
Hi there,

I'm unable to install this package since there's a peer dependency on `electron@20`. Can this be removed or set to something like `>= 20`?

**Comment by daltonmenezes** [comment]
Hi @offirgolan , could you please test v1.0.2 and see if the issue is resolved?
```bash
npm i electron-router-dom
```

**Comment by omBratteng** [comment]
I can confirm this is working now. Could you also please push the changes to github, as they don't show any changes since release of v1.0.0.

**Comment by daltonmenezes** [comment]
Done, thanks @omBratteng @offirgolan 💜

**Comment by offirgolan** [comment]
Confirmed working on my end as well. Thanks for the quick fix and release!
