### ISSUE TITLE
Router dom not work on production

### ISSUE THREAD

**Issue by SelinaVan** [daltonmenezes/electron-router-dom#16]
I'm using electron router dom and react router dom, the router work very well on development environment but after build, the screen is empty.
Does anyone can help me to solve this issue
My source code like this

// electron > main.ts
const { app, BrowserWindow, ipcMain } = require('electron');
// const electronDebug = require('electron-debug');
const path = require('path');
const User = require('./models/User');
const Resume = require('./models/Resume');
const bcrypt = require('bcryptjs');
const {createURLRoute} = require('electron-router-dom')

function createWindow() {
  win = new BrowserWindow({
    icon: path.join(process.env.VITE_PUBLIC, 'electron-vite.svg'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  });

  // Test active push message to Renderer-process.
  win.webContents.on('did-finish-load', () => {
    win?.webContents.send('main-process-message', new Date().toLocaleString());
  });

  if (VITE_DEV_SERVER_URL) {
    win.loadURL(createURLRoute(VITE_DEV_SERVER_URL,
      'main',
    ));
  } else {
    // win.loadFile('dist/index.html')
    win.loadFile(path.join(process.env.DIST, 'index.html'));
  }
}

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
    win = null;
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(createWindow);

** App.tsx

function App() {

  const dispatch = useDispatch();
 

  return (
    <ThemeProvider>
      <CssBaseline />
      <Router
        main={
            <>
              <Route path='/' element={<BaseLayout><SignInUpPage /></BaseLayout>} />
              <Route path='/signIn' element={<BaseLayout><SignInUpPage /></BaseLayout>} />
              <Route path='/signUp' element={<BaseLayout><SignInUpPage /></BaseLayout>} />
              <Route path='/resume' element={<SidebarLayout><Resumepage /></SidebarLayout>} />
            </>
        }
      />
    </ThemeProvider>
  );
}
export default App;

** main.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom/client';
import App from './App.tsx';
import store from './store';
import { Provider } from 'react-redux';

// Declare ipcRenderer on the window object
declare global {
  interface Window {
    ipcRenderer: any;
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
      <Provider store={store}>
        <App />
      </Provider>
  </React.StrictMode>
);

// Remove Preload scripts loading
postMessage({ payload: 'removeLoading' }, '*');

**Comment by SelinaVan** [comment]
Leftside is dev, and another is prod
![Screenshot 2024-01-31 at 14 38 54](https://github.com/daltonmenezes/electron-router-dom/assets/110537992/af81c2cf-773e-4bc5-b65f-5f18960ab68a)

**Comment by SelinaVan** [comment]
photo to easy view
![Uploading Screenshot 2024-01-31
![Screenshot 2024-01-31 at 14 42 38](https://github.com/daltonmenezes/electron-router-dom/assets/110537992/e08ad619-0dee-4bfe-93cb-6257bee58282)

![Screenshot 2024-01-31 at 14 41 10](https://github.com/daltonmenezes/electron-router-dom/assets/110537992/1c635d93-df59-426c-8327-572325ba1bd4)
 at 14.40.31.png…]()

**Comment by csanchez-jetdev** [comment]
Hello @SelinaVan, how did you solve your problem ?

I have a similar issue, it doesn't work on production but only on windows. It's seem that the router add a "C:" before routing ...
