### ISSUE TITLE
Readme is missing how to open a route in a new window

### ISSUE THREAD

**Issue by offirgolan** [daltonmenezes/electron-router-dom#2]
Currently, the readme has the following:

```jsx
// The "App" comes from the context bridge in preload/index.ts
const { App } = window

// ...

<button onClick={App.OpenAboutWindow}>Open About window</button>
```

But it's still unclear how to actually open/close the windows. Can you provide a more in-depth example or a sample application?

**Comment by daltonmenezes** [comment]
Hi @offirgolan , the way to achieve that is an Electron thing, currently the recommended way to go is using IPC. You can check my [electron-app](https://github.com/daltonmenezes/electron-app) boilerplate to see how I achieve that.

- [preload script requesting window creation using IPC](https://github.com/daltonmenezes/electron-app/blob/main/src/preload/ipcs/windows/about/create.ts)
- [window creation on main process using IPC](https://github.com/daltonmenezes/electron-app/blob/main/src/main/windows/About/ipcs/register-window-creation.ts)
- [Routing doc from electron-app](https://github.com/daltonmenezes/electron-app/blob/main/docs/ROUTING.md)

But your question gives me the feeling that I can do better on **electron-router-dom**, I'm thinking it will be a good opportunity to transform this project in a monorepo with some examples. What do you think about it?

**Comment by offirgolan** [comment]
@daltonmenezes those resources were incredibly helpful, thank you! I was able to get this setup today following your boilerplate app.
