### ISSUE TITLE
Handle trailing slash in `createURLRoute`

### ISSUE THREAD

**Issue by offirgolan** [daltonmenezes/electron-router-dom#3]
I came across this issue today where `createURLRoute(import.meta.env.VITE_DEV_SERVER_URL, id)` generated an invalid url because `import.meta.env.VITE_DEV_SERVER_URL` had a trailing `/`. 

The generated URL was something like `http://localhost:1234//#/main`.

I was able to fix it via `url.replace(/\/+$/, '')` but I still think this should be handled by this package.

**Comment by daltonmenezes** [comment]
Hi @offirgolan , could you please test v1.0.3 and see if the issue is resolved?
```bash
npm i electron-router-dom
```

**Comment by offirgolan** [comment]
Appreciate the quick fix but your regex replace breaks file urls (e.g. `file:///User/foo/index.html`)

**Comment by daltonmenezes** [comment]
@offirgolan but **createURLRoute** is not to handle file protocol (dev environment), for file protocol (production environment) you should use **createFileRoute**

**Comment by offirgolan** [comment]
Yeah, all good just wanted to call out an edge case. I did run into a build issue with v1.0.3 though:

```
[ERROR] Could not read from file: /Users/ogolan/src/desktop-app/packages/renderer/src/shared

    node_modules/electron-router-dom/dist/esm/index.js:1:183:
      1 │ ...r-dom";import{removeURLExtraDoubleSlashes as c}from"src/shared";function i(o){return Object.keys(o).reduce((t,e)=>...
        ╵                                                       ~~~~~~~~~~~~

/Users/ogolan/src/desktop-app/node_modules/esbuild/lib/main.js:1566
  let error = new Error(`${text}${summary}`);
```

**Comment by daltonmenezes** [comment]
@offirgolan update to v1.0.4 and test it again, please.

**Comment by offirgolan** [comment]
v1.0.4 hasn't been published 😅

**Comment by daltonmenezes** [comment]
@offirgolan 
https://www.npmjs.com/package/electron-router-dom/v/1.0.4

**Comment by offirgolan** [comment]
Ok, confirmed that it works in 1.0.4! Thanks again for the quick fix 😄
