### ISSUE TITLE
Thoughts on a `createElectronRouter` API to support v6.4 data APIs

### ISSUE THREAD

**Issue by offirgolan** [daltonmenezes/electron-router-dom#7]
👋 Hi! 

v6.4 of react router introduced data APIs that can only be used via the `createBrowserRouter`, `createHashRouter`, and `createMemoryRouter`. 

Thoughts on having this library support a similar wrapper around `createHashRouter`?

**Comment by offirgolan** [comment]
Following up on this. This is what I'm currently doing:

```tsx
import type { FC, ReactNode } from 'react';
import { useMemo } from 'react';
import {
  RouterProvider,
  createHashRouter,
  createRoutesFromChildren,
} from 'react-router-dom';

type Routes = Record<string, ReactNode>;

type AppRouterProps = {
  routes: Routes;
};

function getRouteForCurrentWindow(routes: Routes) {
  const selectAllSlashes = /\//g;
  const windowId = window.location.hash
    .split(selectAllSlashes)?.[1]
    ?.toLowerCase();
  const found = Object.keys(routes).find(
    (key) => key.toLowerCase() === windowId
  );

  return found
    ? {
        basename: `/${windowId}`,
        element: routes[found],
      }
    : null;
}

const AppRouter: FC<AppRouterProps> = ({ routes }) => {
  const router = useMemo(() => {
    const route = getRouteForCurrentWindow(routes);

    return route
      ? createHashRouter(createRoutesFromChildren(route.element), {
          basename: route.basename,
        })
      : null;
  }, [routes]);

  return router ? <RouterProvider router={router} /> : null;
};

export { AppRouter, type AppRouterProps };
```

**Comment by daltonmenezes** [comment]
Hi @offirgolan, I'm worried about implementing that on our side in a scenario where createHashRouter doesn't officially support that (maybe just until this very moment?) and Electron Router DOM is just a bridge to make React Router DOM work in production and development environment on Electron. I need time to think about the path we will take in this regard.

**Comment by daltonmenezes** [comment]
Hi @offirgolan I think I don't quite understand which APIs you are referring to. Could you please talk more about it and include links, so I can take a look? Currently, the way it is, what's the issue using both libs?

**Comment by offirgolan** [comment]
@daltonmenezes this is documented [here](https://reactrouter.com/en/main/routers/picking-a-router#using-v64-data-apis)

![Screen Shot 2022-11-21 at 9 57 53 AM](https://user-images.githubusercontent.com/575938/203126898-7d1be6cb-8579-41ac-b31a-8277fb5efafb.png)

**Comment by daltonmenezes** [comment]
Thanks, @offirgolan . Have you had the following type issues?
![Captura de tela de 2022-11-24 21-12-27](https://user-images.githubusercontent.com/1149845/203876963-fe5855b7-152e-4b39-9cd1-41c8d14f13d5.png)

**Comment by daltonmenezes** [comment]
@offirgolan Ok, the type issue was in v6.4.0, bumping to v6.4.3 solves. 🤔

**Comment by daltonmenezes** [comment]
@offirgolan using **react-router-dom v6.6.0**, but we need a **electron-router-dom breaking-change** to make it work only from that and higher versions. 🤔

https://user-images.githubusercontent.com/1149845/209368713-6914ee48-4707-4baf-87d3-834f6f516dd0.mp4

**Comment by offirgolan** [comment]
@daltonmenezes thanks for taking the time to look into this 😄 

I think a new major version release for this breaking change makes sense since it will be following react-router-dom's new API recommendations.

**Comment by galetahub** [comment]
@daltonmenezes thanks for your work!
Do you have any plans to support react-router-dom 6.x?

**Comment by daltonmenezes** [comment]
@galetahub soon, I'm finishing the new version of [opendocs](https://github.com/daltonmenezes/opendocs), after that I can return to electron-router-dom development

**Comment by daltonmenezes** [comment]
@galetahub @offirgolan 

The initial decisions I made for version 2.0:
- simplify the api, `electron-router-dom` will only export the `Router` from `react-router-dom`, the `Route` and anything else from `react-router-dom` will need to be imported from it and no longer from `electron-router-dom`. I believe this will bring less confusion!
- I added the optional `_providerProps` property, so that you can override the internal `RouterProvider` props
- minimum versions required:
  - react: >=18.0
  - react-router-dom >=6.22.3

what do you think?

![code](https://github.com/user-attachments/assets/927bbbc8-773b-44e6-9a36-47ab8bb840e0)

**Comment by daltonmenezes** [comment]
@galetahub @offirgolan how about this one?

https://github.com/user-attachments/assets/e6065699-e24a-4da9-bc24-f41015fcdd77

**Comment by daltonmenezes** [comment]
@galetahub @offirgolan v2 release planned for this week! Currently working on site, docs and migration guide!

**Comment by daltonmenezes** [comment]
@galetahub @offirgolan v2 released now! 🎉
