### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Ange0** [daltonmenezes/electron-router-dom#8]
![03A2F0D8-EB6D-40CA-9065-DF493799682B](https://user-images.githubusercontent.com/45317331/218756603-69d017ae-513e-4490-9e2e-5c23e9e1e0c8.jpeg)

I use https://evite.netlify.app/ as main stack. Error show when build app (production)

**Comment by daltonmenezes** [comment]
Hi @Ange0 , please provide a reproducible example.
